# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-22 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_message_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='poster',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='posted_comments', to='users.User'),
            preserve_default=False,
        ),
    ]
